#!/usr/bin/env tsx
/**
 * Emits the C# side of the wire protocol from packages/protocol/src/schema.ts.
 *
 * Unity does not play well with package managers inside a monorepo, so generated C#
 * is committed into the Unity project (docs/gearbox/03-architecture.md §3.5 rule 3).
 * CI runs this with --check and fails if the committed output is stale, which is what
 * makes "single source of truth for the wire" true rather than aspirational.
 *
 *   pnpm codegen         write
 *   pnpm codegen:check   verify committed output is current (CI)
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CHANNELS,
  FIELD_SIZES,
  HEADER_SIZE,
  MESSAGES,
  PROTOCOL_VERSION,
  payloadSize,
  type FieldKind,
  type MessageDef,
} from '../src/schema.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(HERE, '../../../apps/xr-client/Assets/GearBox/Generated');
const OUT_FILE = join(OUT_DIR, 'GearBoxProtocol.g.cs');

const CSHARP_TYPES: Record<FieldKind, string> = {
  u8: 'byte',
  u16: 'ushort',
  u32: 'uint',
  i16: 'short',
  f32: 'float',
  vec3q: 'Vector3',
  quat32: 'Quaternion',
};

const READERS: Record<FieldKind, string> = {
  u8: 'r.ReadByte()',
  u16: 'r.ReadUInt16()',
  u32: 'r.ReadUInt32()',
  i16: 'r.ReadInt16()',
  f32: 'r.ReadSingle()',
  vec3q: 'r.ReadQuantizedVector3(bounds)',
  quat32: 'r.ReadPackedQuaternion()',
};

function writerCall(kind: FieldKind, expr: string): string {
  switch (kind) {
    case 'vec3q':
      return `w.WriteQuantizedVector3(${expr}, bounds);`;
    case 'quat32':
      return `w.WritePackedQuaternion(${expr});`;
    case 'u8':
      return `w.Write((byte)${expr});`;
    case 'u16':
      return `w.Write((ushort)${expr});`;
    case 'u32':
      return `w.Write((uint)${expr});`;
    case 'i16':
      return `w.Write((short)${expr});`;
    case 'f32':
      return `w.Write((float)${expr});`;
  }
}

function pascal(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function docComment(text: string | undefined, indent: string): string {
  if (!text) return '';
  return `${indent}/// <summary>${text.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</summary>\n`;
}

function emitStruct(def: MessageDef): string {
  const fields = def.fields
    .map(
      (f) =>
        `${docComment(f.doc, '        ')}        public ${CSHARP_TYPES[f.kind]} ${pascal(f.name)};`,
    )
    .join('\n');

  const writes = def.fields
    .map((f) => `            ${writerCall(f.kind, `msg.${pascal(f.name)}`)}`)
    .join('\n');

  const reads = def.fields
    .map((f) => `            msg.${pascal(f.name)} = ${READERS[f.kind]};`)
    .join('\n');

  return `${docComment(def.doc, '    ')}    public struct ${def.name}
    {
        public const byte MessageId = 0x${def.id.toString(16)};
        public const int PayloadSize = ${payloadSize(def)};

${fields}

        public static void Write(GearBoxWriter w, in ${def.name} msg, in SessionBounds bounds)
        {
${writes}
        }

        public static ${def.name} Read(GearBoxReader r, in SessionBounds bounds)
        {
            var msg = new ${def.name}();
${reads}
            return msg;
        }
    }
`;
}

function emit(): string {
  const header = `// <auto-generated>
//     Generated by packages/protocol/codegen/emit-csharp.ts from
//     packages/protocol/src/schema.ts. DO NOT EDIT BY HAND.
//
//     Regenerate with:  pnpm codegen
//     CI verifies freshness with:  pnpm codegen:check
// </auto-generated>

using UnityEngine;

namespace GearBox.Generated
{
    public static class Protocol
    {
        public const byte Version = ${PROTOCOL_VERSION};
        public const int HeaderSize = ${HEADER_SIZE};

${Object.entries(FIELD_SIZES)
  .map(([k, v]) => `        public const int SizeOf_${k} = ${v};`)
  .join('\n')}
    }

    public enum MessageId : byte
    {
${MESSAGES.map((m) => `        ${m.name} = 0x${m.id.toString(16)},`).join('\n')}
    }

    public enum Channel : byte
    {
${CHANNELS.map((c, i) => `        ${c.name} = ${i},`).join('\n')}
    }

    public static class ChannelInfo
    {
        public static bool IsReliable(Channel c)
        {
            switch (c)
            {
${CHANNELS.map((c) => `                case Channel.${c.name}: return ${c.reliable ? 'true' : 'false'};`).join('\n')}
                default: return true;
            }
        }

        public static int NominalRateHz(Channel c)
        {
            switch (c)
            {
${CHANNELS.map((c) => `                case Channel.${c.name}: return ${c.rateHz};`).join('\n')}
                default: return 0;
            }
        }
    }

    public static class MessageRouting
    {
        public static Channel ChannelFor(MessageId id)
        {
            switch (id)
            {
${MESSAGES.map((m) => `                case MessageId.${m.name}: return Channel.${m.channel};`).join('\n')}
                default: return Channel.CONTROL;
            }
        }

        public static int PayloadSize(MessageId id)
        {
            switch (id)
            {
${MESSAGES.map((m) => `                case MessageId.${m.name}: return ${payloadSize(m)};`).join('\n')}
                default: return -1;
            }
        }
    }

`;

  const structs = MESSAGES.map(emitStruct).join('\n');

  return `${header}${structs}}
`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const content = emit();

  if (check) {
    if (!existsSync(OUT_FILE)) {
      console.error(`[codegen] Missing generated file: ${OUT_FILE}\n[codegen] Run: pnpm codegen`);
      process.exit(1);
    }
    const current = readFileSync(OUT_FILE, 'utf8');
    if (current !== content) {
      console.error(
        `[codegen] ${OUT_FILE} is stale.\n[codegen] The wire schema changed but the generated C# was not committed.\n[codegen] Run: pnpm codegen`,
      );
      process.exit(1);
    }
    console.log('[codegen] Generated C# is up to date.');
    return;
  }

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, content, 'utf8');
  console.log(
    `[codegen] Wrote ${OUT_FILE} (${MESSAGES.length} messages, protocol v${PROTOCOL_VERSION})`,
  );
}

main();
